name: Build & Test Project

on:
  workflow_dispatch:
  push:
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2     # checkout the repo
      - name: install dependencies
      - working-directory: ./App/ba-project        # switch to app
      - run: npm ci                   # install packages
      - run: npm test                 # run tests (configured to use jest-junit reporter)

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Mocha Tests           # Name of the check run which will be created
          working-directory: ./App/ba-project
          path: './test-results.json'   # Path to test results
          reporter: mocha-json        # Format of test results
