name: Build & Test Project



on:
  workflow_dispatch:
  push:
  repository_dispatch:
    types: [Build & Test Project]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2     # checkout the repo
      - name: Build & Test
        working-directory: ./App/ba-project        # switch to app
        run: |
            npm ci                   # install packages
            npm test                 # run tests (configured to use jest-junit reporter)
