name: Heroku-Action
on: push
jobs:
  heroku-action:
    name: build project
    runs-on: ubunte-latest
    steps:
     -  name: building for heroku
  # You may pin to the exact commit or the version.
  # uses: CDNievas/heroku-action@c9cf9c85571e67583e44ec92c0d1113f66b0e838
        uses: behe/heroku-build@v1
        with:
          # Used for authentication. You can find it in your heroku homepage account settings
          api_key: e366affa-fd44-49d5-9053-dcd66c77d1df
          # Email from Heroku Account
          heroku_email: l.gebhardt@integr8.com
          # The appname to use for deploying/updating
          app_name: ba-2021
          # Set if your app is located in a subdirectory.
          path: /app/baba-project # optional, default is 
          # Contents of the Procfile to save and deploy
