name: Heroku Deploy

env:
  REPO_OWNER: leandergebhardti8
  REPO_NAME: ba-2021
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

on: 
  repository_dispatch:
    types: [run-deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ba-2021" #Must be unique in Heroku
          heroku_email: "l.gebhardt@integr8.com"
          appdir: "/App/ba-project" 
