name: Heroku-Action
on: push
jobs:
  heroku-action:
    name: build project
    runs-on: ubuntu-latest
    steps:
     -  name: building for heroku
  # You may pin to the exact commit or the version.
  # uses: CDNievas/heroku-action@c9cf9c85571e67583e44ec92c0d1113f66b0e838
        uses: actions/checkout@v2
     - run: git subtree push --prefix App/ba-project heroku main
