name: Super-Linter

on: 
  push:
  repository_dispatch:
    types: [Super-Linter]

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove files before linting
        run: |
          cd App/ba-project
          rm -rf dist
          rm -rf node_modules

      - name: Lint Code Base
        uses: github/super-linter@v3.17.0
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
